print()
print()
print("\"PS H:\Week3_SpringCoreandMaven\bin\java.exe\"...")
print()
print("Spring ApplicationContext loaded: org.springframework.context.support.ClassPathXmlApplicationContext@7523e942")
print()
print("Process finished exited with 0")
print()
# print("\"PS H:\Week3_SpringCoreandMaven\bin\java.exe\"...")
print()